name: C/C++ CI

on:
    push:
        branches: [main , floatAmigo, newMain]
    pull_request:
        branches: [main , floatAmigo, newMain]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: make
              run: make
            - name: make test
              run: make test
